# Generated by Django 5.0.6 on 2024-06-26 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineID', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('manufacture', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=10)),
                ('line', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('production', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_machine', to='production_monitoring.machine')),
            ],
        ),
    ]
