# Generated by Django 5.0.6 on 2024-06-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncount',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_monitoring.machine'),
        ),
    ]
