# Generated by Django 5.0.6 on 2024-06-25 08:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('missing_date', models.DateField(default=datetime.datetime.now)),
                ('production_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_monitoring.productioncount')),
            ],
        ),
    ]
